import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const SCAN_FRAME_WIDTH = 300;
export const SCAN_FRAME_HEIGHT = 180;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.bg },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  headerTitle: { fontFamily: "Nunito_800ExtraBold", fontSize: 24, color: Colors.text },
  headerSub: {
    fontFamily: "Nunito_400Regular",
    fontSize: 13,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  clearBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.errorLight,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingBottom: 120,
  },
  emptyTitle: { fontFamily: "Nunito_700Bold", fontSize: 20, color: Colors.textSecondary },
  emptyDesc: {
    fontFamily: "Nunito_400Regular",
    fontSize: 14,
    color: Colors.textSecondary,
    textAlign: "center",
    paddingHorizontal: 40,
  },
  listContent: { padding: 12, gap: 8, paddingBottom: 20 },
  itemRow: {
    backgroundColor: Colors.white,
    borderRadius: 14,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  itemInfo: { flex: 1 },
  itemName: { fontFamily: "Nunito_600SemiBold", fontSize: 15, color: Colors.text },
  itemCode: {
    fontFamily: "Nunito_400Regular",
    fontSize: 11,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  itemSerial: {
    fontFamily: "Nunito_400Regular",
    fontSize: 10,
    color: Colors.textSecondary,
    marginTop: 1,
  },
  itemControls: { alignItems: "flex-end", gap: 6 },
  priceInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.bg,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  rupee: { fontFamily: "Nunito_600SemiBold", fontSize: 13, color: Colors.textSecondary },
  priceInput: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 14,
    color: Colors.text,
    minWidth: 60,
    textAlign: "right",
    padding: 0,
  },
  qtyRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  qtyBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.bg,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  qtyText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
    color: Colors.text,
    minWidth: 24,
    textAlign: "center",
  },
  itemTotal: { fontFamily: "Nunito_700Bold", fontSize: 15, color: Colors.primary },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    paddingTop: 12,
    paddingHorizontal: 16,
    gap: 12,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  totalLabel: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 15,
    color: Colors.textSecondary,
  },
  totalAmount: { fontFamily: "Nunito_800ExtraBold", fontSize: 28, color: Colors.primary },
  actionRow: { flexDirection: "row", gap: 10, paddingBottom: 4 },
  manualBtn: {
    flex: 1,
    height: 56,
    borderRadius: 14,
    backgroundColor: Colors.secondaryLight,
    borderWidth: 1,
    borderColor: Colors.secondary + "40",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  manualBtnText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 12,
    color: Colors.secondary,
  },
  scanBtn: {
    flex: 2,
    height: 56,
    borderRadius: 14,
    backgroundColor: Colors.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  scanBtnText: { fontFamily: "Nunito_700Bold", fontSize: 18, color: Colors.white },
  checkoutBtn: {
    flex: 1,
    height: 56,
    borderRadius: 14,
    backgroundColor: Colors.success,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  checkoutBtnDisabled: { backgroundColor: Colors.border },
  checkoutBtnText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 12,
    color: Colors.white,
  },
  checkoutBtnTextDisabled: { color: Colors.textSecondary },


  scannerContainer: { ...StyleSheet.absoluteFillObject, zIndex: 100 },
  scanOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
  },

scanTopBar: {
  position: "absolute",
  top: 120,
  alignSelf: "center",
  zIndex: 3,
  flexDirection: "row",
  gap: 14,
  paddingHorizontal: 18,
  paddingVertical: 10,
  backgroundColor: Colors.bgCard,
  borderRadius: 14,
  alignItems: "center",
},

scanSummary: {
  fontFamily: "Nunito_700Bold",
  fontSize: 18,
  color: Colors.text,
},

scanSummaryAmount: {
  fontFamily: "Nunito_800ExtraBold",
  fontSize: 22,
  color: Colors.success,
},

scanToast: {
  position: "absolute",
  top: 180,
  alignSelf: "center",
  zIndex: 3,
  paddingHorizontal: 20,
  paddingVertical: 10,
  borderRadius: 12,
},

scanToastSuccess: {
  backgroundColor: Colors.success,
},

scanToastError: {
  backgroundColor: Colors.error,
},

scanToastText: {
  fontFamily: "Nunito_700Bold",
  fontSize: 18,
  color: Colors.white,
},

scanBottomBar: {
  position: "absolute",
  bottom: 100,
  width: "100%",
  zIndex: 3,
  flexDirection: "row",
  justifyContent: "center",
  gap: 20,
  paddingHorizontal: 30,
},

scanManualBtn: {
  height: 60,
  width: 150,
  borderRadius: 16,
  backgroundColor: Colors.secondary,
  alignItems: "center",
  justifyContent: "center",
  flexDirection: "row",
  gap: 8,
},

billBtn: {
  height: 60,
  width: 150,
  borderRadius: 16,
  backgroundColor: Colors.primary,
  alignItems: "center",
  justifyContent: "center",
  flexDirection: "row",
  gap: 8,
},

  overlayContainer: {
    ...StyleSheet.absoluteFillObject,
  },
  overlayTop: {
    flex: 1,
    backgroundColor: Colors.primaryDark  + "CC",
  },
  overlayMiddle: {
    flexDirection: "row",
    height: SCAN_FRAME_HEIGHT + 20, // must match scanFrame height
  },
  overlaySide: {
    flex: 1,
    backgroundColor: Colors.primaryDark,
  },
  overlayBottom: {
    flex: 1,
    backgroundColor: Colors.primaryDark  + "CC", 
  },
  scanFrame: {
    width: SCAN_FRAME_WIDTH,
    height: SCAN_FRAME_HEIGHT,
    borderWidth: 2.5,
    borderRadius: 16,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  scanLine: {
    height: 3,
    width: "80%",
    borderRadius: 2,
  },
  scanContent: {
    alignItems: "center",
    justifyContent: "center",
  },
  frameContainer: {
    height: SCAN_FRAME_HEIGHT,
    justifyContent: "center",
    alignItems: "center",
  },
  closeScanBtn: {
    position: "absolute",
    bottom: 300,
    right: 30,
    width: 50,
    height: 50,
    borderRadius: 22,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
  },



  permissionBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    backgroundColor: Colors.bg,
    padding: 32,
  },
  permTitle: { fontFamily: "Nunito_700Bold", fontSize: 20, color: Colors.text },
  permDesc: {
    fontFamily: "Nunito_400Regular",
    fontSize: 14,
    color: Colors.textSecondary,
    textAlign: "center",
  },
  permBtn: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 14,
  },
  permBtnText: { fontFamily: "Nunito_700Bold", fontSize: 15, color: Colors.white },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
  },
  checkoutModal: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
    gap: 16,
  },
  checkoutHandle: {
    width: 40,
    height: 4,
    backgroundColor: Colors.border,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 4,
  },
  checkoutTitle: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 22,
    color: Colors.text,
    textAlign: "center",
  },
  checkoutTotal: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 38,
    color: Colors.primary,
    textAlign: "center",
  },
  inputGroup: { gap: 10 },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: Colors.bg,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    minHeight: 52,
  },
  modalInput: {
    flex: 1,
    fontFamily: "Nunito_400Regular",
    fontSize: 15,
    color: Colors.text,
    padding: 0,
  },
  rupeeLabel: { fontFamily: "Nunito_700Bold", fontSize: 16, color: Colors.textSecondary },
  paymentToggle: { flexDirection: "row", gap: 12 },
  paymentBtn: {
    flex: 1,
    height: 56,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: Colors.border,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  paymentBtnActive: { borderColor: "transparent" },
  paymentBtnText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 15,
    color: Colors.textSecondary,
  },
  paymentBtnTextActive: { color: Colors.white },
  cashSection: { gap: 10 },
  changeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  changeLabel: { fontFamily: "Nunito_600SemiBold", fontSize: 14 },
  changeAmount: { fontFamily: "Nunito_800ExtraBold", fontSize: 18 },
  checkoutActions: { flexDirection: "row", gap: 12, marginTop: 4 },
  cancelBtn: {
    flex: 1,
    height: 56,
    borderRadius: 14,
    backgroundColor: Colors.bg,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelBtnText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 15,
    color: Colors.textSecondary,
  },
  confirmBtn: {
    flex: 2,
    height: 56,
    borderRadius: 14,
    backgroundColor: Colors.success,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  confirmBtnText: { fontFamily: "Nunito_700Bold", fontSize: 15, color: Colors.white },
});
